name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: cargo build
    strategy:
      matrix:
        rust: [stable, beta, nightly]
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        default: true
        override: true
        toolchain: ${{matrix.rust}}
    - name: build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release

  test:
    name: cargo test
    strategy:
      matrix:
        rust: [stable, beta, nightly]
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        default: true
        override: true
        toolchain: ${{matrix.rust}}
    - name: test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --release

  doc:
    name: cargo doc
    strategy:
      matrix:
        rust: [stable, beta, nightly]
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        default: true
        override: true
        toolchain: ${{matrix.rust}}
    - name: doc
      uses: actions-rs/cargo@v1
      with:
        command: doc
        args: --no-deps --release
    - name: doc-tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --doc --release

  fmt:
    name: cargo fmt
    strategy:
      matrix:
        rust: [stable, beta, nightly]
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        default: true
        override: true
        toolchain: ${{matrix.rust}}
        components: rustfmt
    - name: format
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

  clippy:
    name: cargo clippy
    strategy:
      matrix:
        rust: [stable, beta, nightly]
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        default: true
        override: true
        toolchain: ${{matrix.rust}}
        components: clippy
    - name: check
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D clippy::all
